spring.application.name=Menu-Analyzer

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/menuanalyzer
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=LS@8367mkk*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# OCR.Space API Configuration
ocr.space.api.key=8457735abe88957

# Spoonacular API Configuration
spoonacular.api.key=7d40e2286c244aa695c3250e3f182c69
spoonacular.api.url=https://api.spoonacular.com
